[project]
name = "other"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "utils-package @file:///Users/lorencp/PycharmProjects/udps-python-workshop/02_playground_uv/packages/packages/utils-package",
]

#[build-system]
#requires = ["hatchling >= 1.26"]
#build-backend = "hatchling.build"
#
#[tool.hatch.build.targets.wheel]
#packages = ["."]