[project]
name = "backend-package"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "utils-package",
]

[tool.uv.sources]
utils-package = { path = "../utils-package", editable = true }

#[build-system]
#requires = ["hatchling >= 1.26"]
#build-backend = "hatchling.build"
#
#[tool.hatch.build.targets.wheel]
#packages = ["src/backend_package"]